component someText {

    Rectangle {
        border-color: #444444;
        background: #2b2b2b;
        border-radius: 20px;
        height: 50px;
        width: parent.width + 20px;

        // Задаем вертикальное и горизонтальное выравнивание для текстового элемента
        Text {
            text: "Hello, PointHub!";
            font-size: 24px;
            color: #e4e4e4;
            vertical-alignment: top; // Вертикальное выравнивание (возможно, это не обязательно)
            horizontal-alignment: left; // Горизонтальное выравнивание
            
            // Убираем отступы
            padding: 0;
        }
    }
}   
export component MainWindow inherits Window {
    width: 1230px;
    height: 690px;
    title: "PointHub";
    icon: @image-url("../assets/icon.png");
    someText{}
}
