
import { someButton } from "someButton.slint";
export component MainWindow inherits Window {
    width: 1230px;
    height: 690px;
    title: "PointHub";

    property <int> count: 0;
    HorizontalLayout {
        for i in count :Image {
            source: @image-url("../assets/icon.png");
        }
    }
    
    Rectangle {
        border-color: black;
        background: white;
        border-width: 2px;
        border-radius: 20px;
        width: 400px;
        height: 100px;
        y: 0px;
        Text {
            text: "Total clicks: " + count;
            font-size: 30px;
            color: black;
        }
        TouchArea {
            clicked => {
                count = count + 1;
            }
        }
    }
}
